export interface Player {
  id: string;
  name: string;
  role: 'Batsman' | 'Bowler' | 'All-Rounder' | 'Wicketkeeper';
  nationality: 'Indian' | 'Overseas';
  rating: number; // 70 to 99
  popularity: number; // 1 to 10 (influences bot bidding wars)
  basePrice: number; // In Crores, e.g. 2.0 or 0.5
  battingStyle: string;
  bowlingStyle: string;
  recentForm: string[]; // Recent scores or bowling figures
  previousTeam: string;
  age: number;
}

export const PLAYER_POOL: Player[] = [
  // BATSMEN
  {
    id: "p1",
    name: "Virat Kohli",
    role: "Batsman",
    nationality: "Indian",
    rating: 96,
    popularity: 10,
    basePrice: 2.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium",
    recentForm: ["113*", "47", "51", "92", "42"],
    previousTeam: "RCB",
    age: 37
  },
  {
    id: "p2",
    name: "Rohit Sharma",
    role: "Batsman",
    nationality: "Indian",
    rating: 93,
    popularity: 9,
    basePrice: 2.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    recentForm: ["68", "49", "105*", "36", "4"],
    previousTeam: "MI",
    age: 39
  },
  {
    id: "p3",
    name: "Travis Head",
    role: "Batsman",
    nationality: "Overseas",
    rating: 94,
    popularity: 9,
    basePrice: 2.0,
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm offbreak",
    recentForm: ["89", "0", "133", "58", "63"],
    previousTeam: "SRH",
    age: 32
  },
  {
    id: "p4",
    name: "Yashasvi Jaiswal",
    role: "Batsman",
    nationality: "Indian",
    rating: 92,
    popularity: 8,
    basePrice: 1.5,
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm legbreak",
    recentForm: ["104*", "24", "67", "53", "35"],
    previousTeam: "RR",
    age: 24
  },
  {
    id: "p5",
    name: "Suryakumar Yadav",
    role: "Batsman",
    nationality: "Indian",
    rating: 95,
    popularity: 9,
    basePrice: 2.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium",
    recentForm: ["102*", "56", "78", "14", "31"],
    previousTeam: "MI",
    age: 35
  },
  {
    id: "p6",
    name: "Shubman Gill",
    role: "Batsman",
    nationality: "Indian",
    rating: 91,
    popularity: 8,
    basePrice: 2.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    recentForm: ["104", "16", "35", "72", "8"],
    previousTeam: "GT",
    age: 26
  },
  {
    id: "p7",
    name: "Ruturaj Gaikwad",
    role: "Batsman",
    nationality: "Indian",
    rating: 89,
    popularity: 7,
    basePrice: 1.5,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    recentForm: ["98", "62", "108*", "32", "46"],
    previousTeam: "CSK",
    age: 29
  },
  {
    id: "p8",
    name: "Rinku Singh",
    role: "Batsman",
    nationality: "Indian",
    rating: 86,
    popularity: 8,
    basePrice: 1.0,
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm offbreak",
    recentForm: ["26*", "16*", "53*", "9", "33*"],
    previousTeam: "KKR",
    age: 28
  },
  {
    id: "p9",
    name: "Faf du Plessis",
    role: "Batsman",
    nationality: "Overseas",
    rating: 87,
    popularity: 7,
    basePrice: 1.5,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    recentForm: ["64", "55", "3", "44", "71"],
    previousTeam: "RCB",
    age: 41
  },

  // WICKETKEEPERS
  {
    id: "p10",
    name: "MS Dhoni",
    role: "Wicketkeeper",
    nationality: "Indian",
    rating: 88,
    popularity: 10,
    basePrice: 1.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium",
    recentForm: ["28*", "37*", "9*", "1*", "20"],
    previousTeam: "CSK",
    age: 44
  },
  {
    id: "p11",
    name: "Heinrich Klaasen",
    role: "Wicketkeeper",
    nationality: "Overseas",
    rating: 94,
    popularity: 9,
    basePrice: 2.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    recentForm: ["42", "67*", "10", "81", "56"],
    previousTeam: "SRH",
    age: 34
  },
  {
    id: "p12",
    name: "Rishabh Pant",
    role: "Wicketkeeper",
    nationality: "Indian",
    rating: 91,
    popularity: 8,
    basePrice: 2.0,
    battingStyle: "Left-hand bat",
    bowlingStyle: "None",
    recentForm: ["88*", "44", "15", "53", "27"],
    previousTeam: "DC",
    age: 28
  },
  {
    id: "p13",
    name: "Sanju Samson",
    role: "Wicketkeeper",
    nationality: "Indian",
    rating: 89,
    popularity: 7,
    basePrice: 1.5,
    battingStyle: "Right-hand bat",
    bowlingStyle: "None",
    recentForm: ["71*", "68", "18", "86", "41"],
    previousTeam: "RR",
    age: 31
  },
  {
    id: "p14",
    name: "Jos Buttler",
    role: "Wicketkeeper",
    nationality: "Overseas",
    rating: 93,
    popularity: 9,
    basePrice: 2.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "None",
    recentForm: ["107*", "100*", "8", "34", "15"],
    previousTeam: "RR",
    age: 35
  },
  {
    id: "p15",
    name: "Nicholas Pooran",
    role: "Wicketkeeper",
    nationality: "Overseas",
    rating: 92,
    popularity: 8,
    basePrice: 1.5,
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm offbreak",
    recentForm: ["75*", "61", "12", "48", "36"],
    previousTeam: "LSG",
    age: 30
  },
  {
    id: "p16",
    name: "Quinton de Kock",
    role: "Wicketkeeper",
    nationality: "Overseas",
    rating: 87,
    popularity: 7,
    basePrice: 1.5,
    battingStyle: "Left-hand bat",
    bowlingStyle: "None",
    recentForm: ["54", "6", "10", "81", "19"],
    previousTeam: "LSG",
    age: 33
  },

  // ALL-ROUNDERS
  {
    id: "p17",
    name: "Hardik Pandya",
    role: "All-Rounder",
    nationality: "Indian",
    rating: 92,
    popularity: 8,
    basePrice: 2.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    recentForm: ["39 & 3/31", "46 & 1/26", "10 & 0/41", "2 & 2/22"],
    previousTeam: "MI",
    age: 32
  },
  {
    id: "p18",
    name: "Ravindra Jadeja",
    role: "All-Rounder",
    nationality: "Indian",
    rating: 91,
    popularity: 8,
    basePrice: 2.0,
    battingStyle: "Left-hand bat",
    bowlingStyle: "Slow left-arm orthodox",
    recentForm: ["43* & 1/22", "15 & 3/18", "7 & 2/25", "31* & 0/30"],
    previousTeam: "CSK",
    age: 37
  },
  {
    id: "p19",
    name: "Glenn Maxwell",
    role: "All-Rounder",
    nationality: "Overseas",
    rating: 89,
    popularity: 8,
    basePrice: 2.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    recentForm: ["28 & 0/28", "4 & 2/15", "0 & 0/34", "32 & 1/20"],
    previousTeam: "RCB",
    age: 37
  },
  {
    id: "p20",
    name: "Andre Russell",
    role: "All-Rounder",
    nationality: "Overseas",
    rating: 93,
    popularity: 9,
    basePrice: 2.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast",
    recentForm: ["41* & 2/25", "27 & 1/19", "24* & 3/18", "9 & 0/30"],
    previousTeam: "KKR",
    age: 38
  },
  {
    id: "p21",
    name: "Sunil Narine",
    role: "All-Rounder",
    nationality: "Overseas",
    rating: 94,
    popularity: 9,
    basePrice: 2.0,
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm offbreak",
    recentForm: ["81 & 1/22", "26 & 2/18", "109 & 0/32", "6 & 1/24"],
    previousTeam: "KKR",
    age: 38
  },
  {
    id: "p22",
    name: "Axar Patel",
    role: "All-Rounder",
    nationality: "Indian",
    rating: 89,
    popularity: 7,
    basePrice: 1.5,
    battingStyle: "Left-hand bat",
    bowlingStyle: "Slow left-arm orthodox",
    recentForm: ["66 & 1/24", "15 & 2/19", "0 & 1/28", "29 & 0/15"],
    previousTeam: "DC",
    age: 32
  },
  {
    id: "p23",
    name: "Liam Livingstone",
    role: "All-Rounder",
    nationality: "Overseas",
    rating: 86,
    popularity: 7,
    basePrice: 1.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak/offbreak",
    recentForm: ["21 & 0/18", "40 & 1/12", "53* & 0/28", "15 & 2/10"],
    previousTeam: "PBKS",
    age: 32
  },
  {
    id: "p24",
    name: "Rachin Ravindra",
    role: "All-Rounder",
    nationality: "Overseas",
    rating: 85,
    popularity: 8,
    basePrice: 1.0,
    battingStyle: "Left-hand bat",
    bowlingStyle: "Slow left-arm orthodox",
    recentForm: ["61 & 0/20", "0 & 1/18", "21 & 0/15", "37 & 0/8"],
    previousTeam: "CSK",
    age: 26
  },

  // BOWLERS
  {
    id: "p25",
    name: "Jasprit Bumrah",
    role: "Bowler",
    nationality: "Indian",
    rating: 98,
    popularity: 10,
    basePrice: 2.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast",
    recentForm: ["3/21", "2/17", "5/21", "0/18", "3/15"],
    previousTeam: "MI",
    age: 32
  },
  {
    id: "p26",
    name: "Pat Cummins",
    role: "Bowler",
    nationality: "Overseas",
    rating: 94,
    popularity: 9,
    basePrice: 2.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast",
    recentForm: ["3/43", "1/28", "2/35", "1/20", "2/29"],
    previousTeam: "SRH",
    age: 33
  },
  {
    id: "p27",
    name: "Mitchell Starc",
    role: "Bowler",
    nationality: "Overseas",
    rating: 92,
    popularity: 9,
    basePrice: 2.0,
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm fast",
    recentForm: ["3/34", "2/14", "1/28", "0/45", "3/20"],
    previousTeam: "KKR",
    age: 36
  },
  {
    id: "p28",
    name: "Rashid Khan",
    role: "Bowler",
    nationality: "Overseas",
    rating: 95,
    popularity: 9,
    basePrice: 2.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    recentForm: ["2/24", "1/18", "0/22", "3/20", "2/31"],
    previousTeam: "GT",
    age: 27
  },
  {
    id: "p29",
    name: "Yuzvendra Chahal",
    role: "Bowler",
    nationality: "Indian",
    rating: 88,
    popularity: 8,
    basePrice: 1.5,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    recentForm: ["3/31", "1/28", "2/19", "0/40", "1/25"],
    previousTeam: "RR",
    age: 35
  },
  {
    id: "p30",
    name: "Kuldeep Yadav",
    role: "Bowler",
    nationality: "Indian",
    rating: 90,
    popularity: 8,
    basePrice: 1.5,
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm wrist spin",
    recentForm: ["2/22", "3/20", "4/19", "1/28", "2/35"],
    previousTeam: "DC",
    age: 31
  },
  {
    id: "p31",
    name: "Mohammed Shami",
    role: "Bowler",
    nationality: "Indian",
    rating: 91,
    popularity: 8,
    basePrice: 2.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast",
    recentForm: ["3/18", "2/25", "4/22", "1/31", "2/20"],
    previousTeam: "GT",
    age: 35
  },
  {
    id: "p32",
    name: "Trent Boult",
    role: "Bowler",
    nationality: "Overseas",
    rating: 89,
    popularity: 8,
    basePrice: 1.5,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Left-arm fast-medium",
    recentForm: ["3/22", "0/35", "1/24", "2/18", "1/29"],
    previousTeam: "RR",
    age: 36
  },
  {
    id: "p33",
    name: "Kagiso Rabada",
    role: "Bowler",
    nationality: "Overseas",
    rating: 90,
    popularity: 8,
    basePrice: 2.0,
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm fast",
    recentForm: ["1/26", "2/32", "3/18", "2/40", "0/22"],
    previousTeam: "PBKS",
    age: 31
  },
  {
    id: "p34",
    name: "Arshdeep Singh",
    role: "Bowler",
    nationality: "Indian",
    rating: 88,
    popularity: 7,
    basePrice: 1.5,
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm medium-fast",
    recentForm: ["4/29", "2/30", "1/24", "3/31", "0/42"],
    previousTeam: "PBKS",
    age: 27
  },
  {
    id: "p35",
    name: "Matheesha Pathirana",
    role: "Bowler",
    nationality: "Overseas",
    rating: 89,
    popularity: 8,
    basePrice: 1.5,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast (slingshot)",
    recentForm: ["4/28", "2/15", "1/22", "3/21", "2/35"],
    previousTeam: "CSK",
    age: 23
  },
  {
    id: "p36",
    name: "Mayank Yadav",
    role: "Bowler",
    nationality: "Indian",
    rating: 84,
    popularity: 8,
    basePrice: 0.75,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast (155+ kmh)",
    recentForm: ["3/14", "3/20", "1/41", "0/13", "1/25"],
    previousTeam: "LSG",
    age: 23
  },
  {
    id: "p37",
    name: "Sandeep Sharma",
    role: "Bowler",
    nationality: "Indian",
    rating: 83,
    popularity: 6,
    basePrice: 0.75,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium-fast",
    recentForm: ["5/18", "2/22", "1/25", "2/32", "0/26"],
    previousTeam: "RR",
    age: 33
  },
  {
    id: "p38",
    name: "T Natarajan",
    role: "Bowler",
    nationality: "Indian",
    rating: 84,
    popularity: 6,
    basePrice: 0.75,
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm medium (yorker)",
    recentForm: ["4/19", "2/32", "1/28", "3/24", "2/41"],
    previousTeam: "SRH",
    age: 35
  },
  {
    id: "p39",
    name: "Harshal Patel",
    role: "Bowler",
    nationality: "Indian",
    rating: 85,
    popularity: 7,
    basePrice: 1.0,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium-fast (dipper)",
    recentForm: ["3/15", "2/38", "3/24", "1/40", "3/21"],
    previousTeam: "PBKS",
    age: 35
  },
  {
    id: "p40",
    name: "Mohit Sharma",
    role: "Bowler",
    nationality: "Indian",
    rating: 82,
    popularity: 6,
    basePrice: 0.75,
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium-fast",
    recentForm: ["1/28", "2/32", "0/40", "3/18", "1/36"],
    previousTeam: "GT",
    age: 37
  }
];

export const PRESETS_AVATARS = [
  { id: "av1", name: "CSK Lion", icon: "🦁", color: "from-yellow-400 to-amber-500" },
  { id: "av2", name: "MI Eagle", icon: "🦅", color: "from-blue-500 to-indigo-600" },
  { id: "av3", name: "RCB Tiger", icon: "🐅", color: "from-red-500 to-rose-700" },
  { id: "av4", name: "KKR Knight", icon: "🛡️", color: "from-purple-600 to-indigo-700" },
  { id: "av5", name: "SRH Sun", icon: "🔥", color: "from-orange-500 to-red-600" },
  { id: "av6", name: "RR Crown", icon: "👑", color: "from-pink-500 to-blue-500" },
  { id: "av7", name: "DC Tiger", icon: "⚡", color: "from-cyan-500 to-blue-700" },
  { id: "av8", name: "LSG Wings", icon: "🪽", color: "from-sky-400 to-indigo-500" },
  { id: "av9", name: "GT Titan", icon: "🔱", color: "from-slate-700 to-slate-900" },
  { id: "av10", name: "PBKS King", icon: "⚔️", color: "from-red-600 to-silver-500" },
];
